services:
  - type: web
    name: power-ladder-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python append_prediction.py"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: vertical-hook-454512-j7-923cfa34df58.json
