services:
  - type: web
    name: power-ladder-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python append_prediction.py"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: service_account.json
